/**
 * DO NOT EDIT THIS FILE
 * COPY THIS FILE AS "db.ts" AND PUT YOUR OWN VALUES
 */

export default {
    webhook: [
        {
            address: "address around where we will search for restaurants",
            bot: {
                icon_url: "icon url you want to diplay",
                username: "your bot's name",
            },
            channel: "the channel in which we'll post, without #",
            cron: "a cron, in the cron format",
        },
    ],
};
