/**
 * DO NOT EDIT THIS FILE
 * COPY THIS FILE AS "parameters.ts" AND PUT YOUR OWN VALUES
 */

export default {
    googlemaps: {
        geocoding: {
            apikey: "your api key",
        },
        nearby: {
            apikey: "your api key",
        },
    },
    listening_port: 3000,
    incoming_webhook: "url to your webhook"
};
